language: python

python:
  - "2.7"
jdk:
  - openjdk7

# command to install dependencies
install:
  - "echo $(whereis java)" 
  - "pip install -r requirements.txt"
# command to run tests
script: python -m tests.integration_test