language: python

python:
  - "2.7"

# command to install dependencies

before_install:
  - "sudo apt-get install openjdk-7-jdk"
  - "sudo apt-get install libfreetype6-dev"
  - "sudo apt-get install python-tk"
install:
  - "pip install -r requirements.txt"
# command to run tests
script: python -m tests.integration_test