sudo: required

language: python

python:
  - "2.7"

# command to install dependencies
# see http://stackoverflow.com/questions/11114225/installing-scipy-and-numpy-using-pip
before_install:
  - "echo $(ls /usr/lib/jvm)" # what jdk do we have?
  - "sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran" # scipy needs this, go figure
  - "sudo apt-get install python-pip"
  - "sudo apt-get install python-setuptools"
  - "sudo apt-get install python-scipy"
  - "sudo apt-get install python-matplotlib"
  - "sudo apt-get install python-nltk"
  - "sudo apt-get install libfreetype6-dev"
  - "sudo apt-get install python-tk"
  - "pip install --upgrade pip" # to make sure we have the latest pip

# make pip see global stuff
virtualenv:
  system_site_packages: true

install:
  - "pip install -r requirements.txt"
# command to run tests
script: python -m tests.integration_test